import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";

// Ensure a LOCATION_PLAN document exists when project has address and parcels (auto location plan)
export async function POST(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getSession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const { id } = await params;
  const project = await prisma.project.findFirst({
    where: { id, userId: user.id },
  });
  if (!project) return NextResponse.json({ error: "Not found" }, { status: 404 });

  const hasAddress = !!project.address?.trim();
  const hasParcels = !!(project.parcelIds?.trim() || project.coordinates);
  if (!hasAddress || !hasParcels) {
    return NextResponse.json({
      ensured: false,
      reason: "Project needs address and parcels to auto-generate location plan",
    });
  }

  const existing = await prisma.document.findFirst({
    where: { projectId: id, type: "LOCATION_PLAN" },
  });
  if (existing) {
    return NextResponse.json({ ensured: true, documentId: existing.id });
  }

  const doc = await prisma.document.create({
    data: {
      projectId: id,
      type: "LOCATION_PLAN",
      name: `${project.name} - Location Plan`,
      metadata: { autoGenerated: true, generatedAt: new Date().toISOString() },
      creditsUsed: 0,
    },
  });
  return NextResponse.json({ ensured: true, documentId: doc.id });
}
