import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getSession } from "@/lib/auth";

export async function GET() {
  const user = await getSession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  const projects = await prisma.project.findMany({
    where: { userId: user.id },
    orderBy: { updatedAt: "desc" },
    include: {
      regulatoryAnalysis: { select: { id: true, zoneType: true } },
      _count: { select: { documents: true } },
    },
  });
  return NextResponse.json({ projects });
}

export async function POST(request: NextRequest) {
  const user = await getSession();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  try {
    const body = await request.json();
    const { name, description, address, municipality, parcelIds, parcelArea, parcelGeometry, parcelsGeoJSON, coordinates, citycode, zoneType, protectedAreas, northAngle, projectType } = body;
    const project = await prisma.project.create({
      data: {
        userId: user.id,
        name: name || "New Project",
        description: description || null,
        address: address || null,
        municipality: municipality || null,
        parcelIds: Array.isArray(parcelIds) ? parcelIds.join(",") : typeof parcelIds === "string" ? parcelIds : "",
        parcelArea: parcelArea ? Number(parcelArea) : null,
        parcelGeometry: typeof parcelGeometry === "string" ? parcelGeometry : (parcelGeometry != null ? JSON.stringify(parcelGeometry) : null),
        parcelsGeoJSON: parcelsGeoJSON ?? null,
        coordinates: coordinates ? JSON.stringify(coordinates) : null,
        citycode: citycode || null,
        northAngle: northAngle != null ? Number(northAngle) : null,
        projectType: projectType && ["construction", "extension", "outdoor", "renovation"].includes(String(projectType)) ? String(projectType) : null,
      },
    });

    // Auto-create LOCATION_PLAN and SITE_PLAN when address and parcels are set
    const hasAddress = !!(address || project.address);
    const hasParcels = !!(Array.isArray(parcelIds) ? parcelIds.length : parcelIds) || !!coordinates;
    if (hasAddress && hasParcels) {
      for (const docType of ["LOCATION_PLAN", "SITE_PLAN"] as const) {
        const existing = await prisma.document.findFirst({
          where: { projectId: project.id, type: docType },
        });
        if (!existing) {
          await prisma.document.create({
            data: {
              projectId: project.id,
              type: docType,
              name: `${project.name} - ${docType === "SITE_PLAN" ? "Site Plan" : "Location Plan"}`,
              metadata: { autoGenerated: true, generatedAt: new Date().toISOString() },
              creditsUsed: 0,
            },
          });
        }
      }
    }

    if (zoneType) {
      await prisma.regulatoryAnalysis.create({
        data: {
          projectId: project.id,
          zoneType: String(zoneType),
          aiAnalysis: { zoneType, fromPluDetection: true },
        },
      });
    }
    if (Array.isArray(protectedAreas) && protectedAreas.length > 0) {
      await prisma.protectedArea.createMany({
        data: protectedAreas.slice(0, 20).map((a: { type?: string; name?: string; description?: string; constraints?: unknown; sourceUrl?: string }) => ({
          projectId: project.id,
          type: (a.type as string) || "INFO",
          name: (a.name as string) || "Protected area",
          description: a.description || null,
          constraints: a.constraints == null ? undefined : (a.constraints as object),
          sourceUrl: a.sourceUrl || null,
        })),
      });
    }

    // ── Pre-process parcel geometry (async, fire-and-forget) ──────────────
    // This runs the full GIS pipeline (merge → boundary → edges → NGF elevations)
    // and saves the result so the site-plan editor can load instantly.
    if (parcelsGeoJSON || parcelGeometry) {
      (async () => {
        try {
          const geoSource = parcelsGeoJSON || (typeof parcelGeometry === "string" ? JSON.parse(parcelGeometry) : parcelGeometry);
          let parcelFeatures: { type: string; properties: Record<string, unknown>; geometry: unknown }[] = [];

          if (geoSource?.type === "FeatureCollection" && Array.isArray(geoSource.features)) {
            parcelFeatures = geoSource.features.filter((f: { geometry?: { type?: string } }) => {
              const gt = f?.geometry?.type;
              return gt === "Polygon" || gt === "MultiPolygon";
            });
          } else if (geoSource?.type === "Feature" && geoSource.geometry) {
            parcelFeatures = [geoSource];
          } else if (geoSource?.type === "Polygon" || geoSource?.type === "MultiPolygon") {
            parcelFeatures = [{ type: "Feature", properties: {}, geometry: geoSource }];
          }

          if (parcelFeatures.length > 0) {
            const baseUrl = process.env.NEXT_PUBLIC_BASE_URL || process.env.VERCEL_URL
              ? `https://${process.env.VERCEL_URL}`
              : "http://localhost:3000";

            const apiPayload = {
              parcels: parcelFeatures.map((f: { type: string; properties?: Record<string, unknown>; geometry: unknown }, idx: number) => ({
                type: f.type,
                properties: {
                  id: (f.properties as Record<string, unknown>)?.id || (f.properties as Record<string, unknown>)?.IDU || `parcel-${idx}`,
                  section: (f.properties as Record<string, unknown>)?.section || (f.properties as Record<string, unknown>)?.SEC || "",
                  number: (f.properties as Record<string, unknown>)?.number || (f.properties as Record<string, unknown>)?.NUM || "",
                  area: (f.properties as Record<string, unknown>)?.area || (f.properties as Record<string, unknown>)?.contenance || 0,
                },
                geometry: f.geometry,
              })),
            };

            const res = await fetch(`${baseUrl}/api/projects/process-geometry`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify(apiPayload),
            });

            if (res.ok) {
              const processedData = await res.json();
              // eslint-disable-next-line @typescript-eslint/no-explicit-any
              await (prisma.project.update as any)({
                where: { id: project.id },
                data: { processed_site_data: processedData },
              });
              console.log(`[project-create] Pre-processed site data saved for project ${project.id}`);
            } else {
              console.warn(`[project-create] process-geometry failed for project ${project.id}: ${res.status}`);
            }
          }
        } catch (err) {
          console.warn("[project-create] Background process-geometry error:", err);
        }
      })();
    }

    return NextResponse.json({ project });
  } catch (error) {
    console.error("Create project:", error);
    return NextResponse.json({ error: "Failed to create project" }, { status: 500 });
  }
}

